services:

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=b3pFUXqvMMx2JS8qLdrt
      - POSTGRES_USER=auction
      - POSTGRES_DB=auction

  auction:
    build: src/Auctions
    restart: unless-stopped
    ports:
      - "127.0.0.1:7001:7001"
    environment:
      - SQL_PASSWORD=b3pFUXqvMMx2JS8qLdrt
      - PORT=7001
      - DEBUG=1
    

volumes:
  psql_data:
